### ISSUE TITLE
Failed without error

### ISSUE THREAD

**Issue by krzkaczor** [peter-evans/create-pull-request#1027]
### Subject of the issue

Action fails without any visible reason why.

![image](https://user-images.githubusercontent.com/1814312/148237893-70d64308-931a-4880-900d-126d282510ea.png)

### Steps to reproduce

https://github.com/makerdao/wormhole-integration-tests/runs/4716044797?check_suite_focus=true

**Comment by peter-evans** [comment]
Hi @krzkaczor 

Expand the tabs and you will see the error.
![image](https://user-images.githubusercontent.com/18365890/148309404-cbc751a4-bee8-4f48-8746-b5cd982fb0ad.png)

Running this action on `pull_request` is generally not a good idea because it checks out a commit instead of a branch. See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#events-which-checkout-a-commit) for the explanation. I recommend looking at the [examples](https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md) to get a better idea of how this action works and how to use it.

**Comment by krzkaczor** [comment]
@peter-evans thanks for quick response!

> Expand the tabs and you will see the error.

I would suggest making error more visible, it totally threw me off that it's not there even after expanding the last tab.

> Running this action on pull_request is generally not a good idea because it checks out a commit instead of a branch. See here for the explanation. I recommend looking at the examples to get a better idea of how this action works and how to use it.

Running on PR was just the easiest way to test if it works. I got it under control now, thanks again!
