### ISSUE TITLE
@mention in PR body is not autolinked

### ISSUE THREAD

**Issue by ericis** [peter-evans/create-pull-request#1033]
### Subject of the issue

Mentioning a team or user does not seem to properly autolink.

### Steps to reproduce

See: https://github.com/ourchitecture/hello-cloud/pull/192#issue-1099456516

The team @ourchitecture/hello-cloud-maintainers is not auto-linked in the PR, despite the team having maintainer access to the repo.

The GitHub Actions source code for this is located here:
https://github.com/ourchitecture/hello-cloud/blob/d7ff33a325d53a6852d93a4ebf7c3416280ecf20/.github/workflows/documentation.yml#L8

And, here:
https://github.com/ourchitecture/hello-cloud/blob/d7ff33a325d53a6852d93a4ebf7c3416280ecf20/.github/workflows/documentation.yml#L69

**Comment by peter-evans** [comment]
Hi @ericis 

I don't think this has anything to do with the action itself. Check the visibility of the team. Is it secret or visible?

You mentioned `@ourchitecture/hello-cloud-maintainers` in your issue above. Is it linked properly for you? It's not linked for me because I'm not a member of the org.

![image](https://user-images.githubusercontent.com/18365890/149043790-94c47689-9ad1-4b97-84c5-9cc4fef4ab48.png)

**Comment by ericis** [comment]
Thanks @peter-evans .


Can you see the team?
https://github.com/orgs/ourchitecture/teams/hello-cloud-maintainers/

![Screenshot_20220111-211045_Firefox.jpg](https://user-images.githubusercontent.com/974919/149051547-ec50647f-7edb-42b5-8320-720412c97587.jpg)

**Comment by ericis** [comment]
@peter-evans here is an example of direct mentions working:
https://github.com/ourchitecture/hello-cloud/pull/191#issuecomment-1010562890

By the way, I tried a few variations without success:

- with `@` and without
- with org prefix ("ourchitecture/") and without
- tried `#{...}` just to see

**Comment by peter-evans** [comment]
The example you just linked shows this for me:
![image](https://user-images.githubusercontent.com/18365890/149052409-d9d7c677-1a10-4c6e-8027-01b9147d0677.png)

I don't have access to the team which is why the hovercard doesn't show, but the link is there.

I think the user who makes the comment matters. Your user account is in the org so when you mention the team it links correctly. The automated PR is being created by the github-actions bot user. This is a special account which is linked to the default `GITHUB_TOKEN`. I think what might work is to create the PR using a PAT created on an account that is a member of the org.

**Comment by ericis** [comment]
Makes sense. I'll try with a PAT from the github "system account" (just another account) and will provide an update.

Ultimately, mentioning the team was just an attempt to work-around the issue that I couldn't assign the team to "reviewers" and fell back on assigning the system account with hopes that I could @mention the team.

**Comment by peter-evans** [comment]
For assigning a team as reviewers check this issue which explains the solution: https://github.com/peter-evans/create-pull-request/issues/155#issuecomment-611904487

**Comment by ericis** [comment]
@peter-evans we think alike! I already linked that exact comment in the build's "reviewers" section below. Thank you.

https://github.com/ourchitecture/hello-cloud/blob/c747894eb3d3345e99dccea22e749167069965de/.github/workflows/documentation.yml#L10-L12

```
  # this variable uses a system account since there are permission issues when assigning teams
  # see: https://github.com/peter-evans/create-pull-request/issues/155#issuecomment-611904487
  OUR_AUTODOC_REVIEWERS: "ourchitectureio"
```

**Comment by ericis** [comment]
@peter-evans Thank you. Success! https://github.com/ourchitecture/hello-cloud/pull/196

Both the body `@mention` and the "team-reviewers" field are working properly once I setup a PAT.

Our setup:
- Team named "@ourchitecture/hello-cloud-maintainers" that is granted "Maintainer" access to the repository
- "System" account (just another GitHub account) is assigned to the team and inherits "Maintainer" access to the repository
- Personal Access Token (PAT) generated by the "system" account and saved as a named "Action secret" in the repository
- GitHub Actions updated to use the PAT secret when creating the PR using "team-reviewers" to assign the team as well as mentioning the team in the body of the PR "@ourchitecture/hello-cloud-maintainers"

![image](https://user-images.githubusercontent.com/974919/149414541-718b8311-13f2-4499-819a-92e45545e987.png)
