### ISSUE TITLE
Can't use action with alpine container

### ISSUE THREAD

**Issue by pietdevries94** [peter-evans/create-pull-request#111]
When using this action in a job using an alpine container, the action fails.
```
/usr/bin/docker exec  a9bf6e9e8c37820f154e50cbf7d4208a10d384c7a86ac34c05965fdff55f83e0 sh -c "cat /etc/*release | grep ^ID"
Container distribution is alpine. Running JavaScript Action with external tool: node12_alpine
/__t/Python/3.8.1/x64/bin/pip install --requirement /__w/_actions/peter-evans/create-pull-request/master/dist/src/requirements.txt --no-index --find-links=/__w/_actions/peter-evans/create-pull-request/master/dist/vendor
##[error]There was an error when attempting to execute the process '/__t/Python/3.8.1/x64/bin/pip'. This may indicate the process failed to start. Error: spawn /__t/Python/3.8.1/x64/bin/pip ENOENT
##[error]Node run failed with exit code 1
```

**Comment by peter-evans** [comment]
Any actions or workflows that rely on binaries in the GitHub Actions tool cache will have compatibility problems when run in Alpine Linux containers. The tool cache doesn't have separate binaries for Alpine so it will install `linux` platform binaries. For example, all the the official `setup-*` actions such as `setup-python`, `setup-go`, etc., install binaries from the tool cache. So those installed binaries very likely don't work in an Alpine Linux container.

I've made a [small fix](https://github.com/peter-evans/create-pull-request/commit/6df2a462d1b2df3cc60ecf1004e992d29cac405c) to the action and now it's possible to run inside an Alpine Linux container by pre-installing the correct binaries for the action's dependencies.

This is an example workflow that installs git and Python at the start of the job. You can also bake these dependencies into your own Alpine Docker image if you prefer that. Note that git must be installed *before* running `actions/checkout`, otherwise it will just download the source of the repository instead of cloning it.

```
jobs:
  createPullRequestAlpine:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
      - name: Install dependencies
        run: |
          apk --no-cache add git python3
          ln -sf python3 /usr/bin/python
          ln -sf pip3 /usr/bin/pip

      - uses: actions/checkout@v2

      - name: Create report file
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by peter-evans** [comment]
Added to the documentation here: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#using-in-an-alpine-linux-container

Thank you for raising this issue!

**Comment by menny** [comment]
I'm using a ubuntu container, and saw the same error.
I add to _fake_ the container to look like Alpine (https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/.github/workflows/packs_md_update.yml#L19) to make this work.

**Comment by peter-evans** [comment]
@menny Thanks for reporting your use case. I'm reopening this issue because clearly the action needs to be a bit more intelligent about whether or not to install Python from the GitHub Actions tool cache.

I notice the [base image](https://hub.docker.com/r/menny/android/dockerfile) for your container is Ubuntu, so I'm a bit confused why the python and pip binaries from the tool cache don't run. Perhaps it's something to do with this line.

```
dpkg --add-architecture i386
```

**Comment by peter-evans** [comment]
Actually, the problem in this case is that there is a missing shared library. On the hosted VMs, `/usr/local/lib` contains these shared libraries I think.
```
python: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
##[error]Process completed with exit code 127.
```
It may not be possible to use Python from the GitHub Actions tool cache when running in *any* container. I might just need to make it a requirement that if you run the action in a container you must pre-install Python and git.

**Comment by peter-evans** [comment]
I've released a fix that detects if the action is running in a container and assumes `python3` and `pip3` are on the `PATH`. Documentation is updated [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#running-in-a-container).

@menny This new fix now means that you don't need to fake running in alpine or create the symlinks. The base image of `menny/ndk_ask:1.13.6` already installs Python 3 so it should just work.

**Comment by menny** [comment]
great! thanks!

I'll update my workflows.

**Comment by menny** [comment]
reporting back that it works as expected now. Thank you.
