### ISSUE TITLE
Users now must explicitly allow creation of pull requests by GitHub actions

### ISSUE THREAD

**Issue by channelbeta** [peter-evans/create-pull-request#1175]
### Users must explicitly allow creation of pull requests by GitHub actions

According to this change: https://github.blog/changelog/2022-05-03-github-actions-prevent-github-actions-from-creating-and-approving-pull-requests/

tl;dr
> The Allow GitHub Actions to create and approve pull requests setting can be managed by admins in organization settings under Actions > General > Workflow permissions.

### Steps to reproduce

If the option is not ticked *for the organization*, the action will fail:

```text
Create or update the pull request
  Attempting creation of pull request
  Error: GitHub Actions is not permitted to create or approve pull requests.
```

### Fix

Add a note on the README maybe?

**Comment by peter-evans** [comment]
Hi @channelbeta 

Thank you. I saw this on the blog, too.

I'll probably add something to the documentation when I figure out where is best to put it. For now, this issue that you have created is good enough for people to find and understand what the problem is. 👍

**Comment by sirosen** [comment]
FWIW, I actually had a little trouble finding this bug report. (Maybe I'm just bad at searching).

Two suggestions:
- pin this issue to make it more prominent in the tracker
- add to docs just before or just after the usage section

I'm happy to open a PR with a doc update if that would be welcome.

Thanks for the awesome project! ❤️

**Comment by peter-evans** [comment]
Added to the readme here: https://github.com/peter-evans/create-pull-request#workflow-permissions

Thank you!

**Comment by aviggiano** [comment]
I was having the same problem because I hadn't approved it on an organization level, and was only trying to do it on the repository level, just because the docs weren't very very very explicit about this. 

I'm referencing a StackOverflow post here for others that might bump into the same problem: 

https://stackoverflow.com/questions/72376229/github-actions-is-not-permitted-to-create-or-approve-pull-requests-createpullre/73155199#73155199
