### ISSUE TITLE
Set `delete-branch=true` by default

### ISSUE THREAD

**Issue by HonkingGoose** [peter-evans/create-pull-request#1233]
### Subject of the issue

The `README.md` says:

| Name | Description | Default |
| --- | --- | --- |
| `delete-branch` | Delete the `branch` when closing pull requests, and when undeleted after merging. Recommend `true`. | `false` |

I think the default behavior should match the recommendation. This means setting `delete-branch=true` in the code.

### Steps to reproduce

1. Check out the `README.md` of this repository.
2. README recommends `delete-branch=true` but code defaults to `delete-branch=false`.

**Comment by peter-evans** [comment]
Hi @HonkingGoose 

This was intentional because when I introduced the `delete-branch` feature I didn't want it to be a breaking behaviour change. Additionally, it's potentially destructive. So for those reasons the default is `false` even though the recommendation is to set it to `true`.

In a future major version release I might decide to make the default `true`. A major release requires users to consciously update, so that would be an acceptable time to make a behaviour change.

**Comment by peter-evans** [comment]
I'm working on changes for the next major version and I've come back to this issue.

I've decided to leave the default as-is. The reason is because users frequently don't read the documentation for this action and just try to use it based on what they think the action inputs mean. Many times this results in users setting an existing branch for the `branch` input. More often than not, it's their default branch or some other important branch like `develop` or `staging`. So to protect these users from accidentally deleting an important branch I think it's best to leave this to `false`. Perhaps I will  remove "Recommend `true`." from the description, since technically it's not necessary to delete the branch. It's just a feature for convenience and for those who like to keep their repos tidy. 😄

**Comment by HonkingGoose** [comment]
Thank you for both of your responses to my idea! Let's keep the default behavior safe for newcomers then. 😄

> Perhaps I will remove "Recommend `true`." from the description, since technically it's not necessary to delete the branch. It's just a feature for convenience and for those who like to keep their repos tidy. 😄

Maybe you can simplify your code (or just the docs), GitHub has a feature called **Automatically delete head branches**: [^quote]

> You can have head branches automatically deleted after pull requests are merged in your repository.

[^quote]: [GitHub Docs, Managing the automatic deletion of branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches)
