### ISSUE TITLE
Getting failed to push some refs to error

### ISSUE THREAD

**Issue by mehdihadeli** [peter-evans/create-pull-request#1608]
Hi,
I have some concurrent jobs that all of them update same file (my application version)

``` yaml
    - name: Create Update Version Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "chore(release): ⬆️ upgrading application version to: ${{ steps.app-version-step.outputs.app-version }} [skip ci]"
        title: "chore(release): ⬆️ upgrading application version to: ${{ steps.app-version-step.outputs.app-version }} [skip ci]"
        delete-branch: true
        branch: upgrade-app-version
        labels: |
          chore
        add-paths: |
          *.Packages.props
```

but some time I get this error:
``` bash
Pushing pull request branch to 'origin/create-pull-request/patch'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/create-pull-request/patch
  To https://github.com/mehdihadeli/ecommerce-microservices
   ! [rejected]        HEAD -> create-pull-request/patch (stale info)
  error: failed to push some refs to 'https://github.com/mehdihadeli/ecommerce-microservices'
  Error: The process '/usr/bin/git' failed with exit code 1
```
Is there any way to force pushing in this situation?

**Comment by peter-evans** [comment]
Hi @mehdihadeli 

I'm assuming that this workflow is running when you merge to the default branch. You want to create a pull request to update the app version for a release? And the problem is that multiple concurrent runs of this workflow conflict because they are all trying to update the same pull request branch.

There's no option to force push, and it probably would not be a good idea to allow it. If the concurrent updates to the pull request branch differ then there is no control over which one would win in that race.

I think in this case I would advise changing the way the workflow to create this PR is triggered. For example, you could run a scheduled workflow every ~15 minutes to create this PR against the default branch. That way it never conflicts.

**Comment by mehdihadeli** [comment]
Hi,
Thanks for your response.
Yes, I think using a scheduling workflow in better for my case.
