### ISSUE TITLE
push to fork runs into an error

### ISSUE THREAD

**Issue by hannesa2** [peter-evans/create-pull-request#1836]
Hi, I try to make a pull request in a fork to the upstream repo, but I see 

https://github.com/gitx/gitx/actions/runs/4638761919/jobs/8208888101

<img width="722" alt="image" src="https://user-images.githubusercontent.com/3314607/230630772-3a2d999b-b879-4a16-a86d-b15e27472335.png">

This is the related pull request https://github.com/gitx/gitx/pull/395
I've no clue what's going on, maybe you see what's wrong here

**Comment by peter-evans** [comment]
Hi @hannesa2 

I can't see anything immediately that looks wrong. The only thing I will say is that this action is designed to work with the official checkout action, so it's possible it's not working because your `Show shasum` step is doing its own checkout.

The action seems to be creating the pull request branches correctly. It's just the pull request creation that returns a 404 for some reason.
https://github.com/Homebrew/homebrew-cask/compare/master...hannesa2:homebrew-cask:bump-gitx-0.23-51-gb682ad51

I'll try to investigate further, but in the meantime, you could try to use the checkout action for checking out `Homebrew/homebrew-cask`.

**Comment by hannesa2** [comment]
Yes, with manual clone I get at least a link to continue manually. That means it's at least semi automated
![image](https://user-images.githubusercontent.com/3314607/230835741-b2731949-2687-477f-853d-524cfba16329.png)

Btw, I added `continue-on-error: true` to have to successful build, to ignore temporary this half automated solution

**Comment by hannesa2** [comment]
Following your idea to use `actions/checkout@v3` to clone https://github.com/gitx/gitx/pull/395/commits/9862fef9d7624412514eabe4ddaa4ff656214c10 
I run into 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/3314607/230837582-5b6577fd-0deb-4266-8a03-b99979d0a386.png">

This is the job https://github.com/gitx/gitx/actions/runs/4654938487/jobs/8237108918

It looks like the `push-to-fork: hannesa2/homebrew-cask` comes with issues, because now there is no branch ?

**Comment by peter-evans** [comment]
When I have some time I'll try and reproduce this issue to debug.

By the way, are you using a fine-grained access token? Or classic?

**Comment by peter-evans** [comment]
I'm testing a similar setup but so far I've been unable to reproduce the issue. It creates the PR ok.
https://github.com/peter-evans/push-to-fork-test/blob/main/.github/workflows/test.yml
Creates: https://github.com/peter-evans/create-pull-request-tests/pull/5703

Please double check that `PERSONALACCESSTOKEN` contains a `repo` scoped PAT that has write access to `hannesa2/homebrew-cask`.

**Comment by hannesa2** [comment]
I gave it these new rights 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/3314607/230931184-30df0194-7aea-4d06-bffc-6d6b063c952a.png">
and it looks like it works now.
Btw, I don't see here a write something.

Thank you for your assistance
