### ISSUE TITLE
Creating Pull request from fork to Upstream

### ISSUE THREAD

**Issue by parteekcoder** [peter-evans/create-pull-request#2021]
### Subject of the issue
Hi everyone, I want to create Pull request to the upstream parent repository automatically when some pushes code to fork, is that possible using this action. If yes can you share the doc where I can find the example for this.

**Comment by peter-evans** [comment]
Hi @parteekcoder 

In your case, the PR branch already exists because I assume you want to merge `fork:main` -> `parent:main`. For this use case this action is not a good fit because the action creates the PR branch itself and maintains it. I recommend just using the [GitHub CLI](https://cli.github.com/manual/gh_pr_create) in a workflow step.
