### ISSUE TITLE
Unable to create pull request across repositories

### ISSUE THREAD

**Issue by francinelucca** [peter-evans/create-pull-request#2135]
### Subject of the issue

We have an action defined in repo "A" that is supposed to update some dependencies and create a pull request in repo "B" of the same organization. It has stopped working recently with error message `Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}`
<img width="816" alt="image" src="https://github.com/peter-evans/create-pull-request/assets/40550942/b6a65019-dca4-425d-a436-4487ae16bffb">

We're checking out to the other repo's base branch before making the changes and attempting to create the pull request but we get the invalid head error nonetheless. 

### Steps to reproduce

Here's our current workflow file: https://github.com/carbon-design-system/carbon/blob/main/.github/workflows/deploy-packages.yml

**Comment by peter-evans** [comment]
Hi @francinelucca 

I'm not sure, but GitHub might be complaining about the format of your branch name.

Setting it like this...
```yml
branch: 'release/update-carbon-deps-${{ github.ref }}'
```
... is causing the branch to be named `release/update-carbon-deps-refs/heads/main`.

Please try removing the `${{ github.ref }}` part of the branch name and just using a fixed name. It doesn't make sense to use `${{ github.ref }}` in your particular workflow because it's always going to be `refs/heads/main`.

Try this:
```yml
branch: 'release/update-carbon-deps'
```

**Comment by francinelucca** [comment]
thanks for the quick turnaround on this @peter-evans , branch naming update did the trick! 
Closing :)
