### ISSUE TITLE
Resets changes in the branch with main

### ISSUE THREAD

**Issue by rprakashg-redhat** [peter-evans/create-pull-request#2243]
I'm trying to use this action to simply open a PR but unfortunately its not working well. I noticed the changes in the branch gets reset with main and pull request never gets creating.

If you want to see the workflow run logs see this link https://github.com/rprakashg-redhat/scheduler/actions/runs/5867887999/job/15909654750

This is the remote repo I want the PR to be opened https://github.com/rprakashg-redhat/scheduler-ops but as you can see the changes in the branch gets reset by this action which is prolly why PR never gets created. If I remove the Open PR job I can correctly see the changes made by the job that updates manifest. Why is this action updating the branch and overwriting changes. I simply need to Open PR 

Not sure what I'm missing

**Comment by Ole-Visma** [comment]
I have the same issue

**Comment by peter-evans** [comment]
Hi @rprakashg-redhat 

Apologies for the slow response.

I think this is because you are trying to use a branch with existing changes to raise in a PR as the `branch` input. (Please correct me if that's not the case)

Please see this section of the common issues doc. (You didn't miss this doc, I just created it)
https://github.com/peter-evans/create-pull-request/blob/main/docs/common-issues.md#create-using-an-existing-branch-as-the-pr-branch
