### ISSUE TITLE
PR is geeting auto merge

### ISSUE THREAD

**Issue by Nayana-Nagaraj** [peter-evans/create-pull-request#2431]
### Subject of the issue PR is geeting auto merge

Describe your issue here. 
While using the action, instead of pr creation its getting auto merged

### Steps to reproduce

If this issue is describing a possible bug please provide (or link to) your GitHub Actions workflow.

**Comment by peter-evans** [comment]
Hi @Nayana-Nagaraj 

You will need to provide more information, and preferably a workflow, in order to try and help you.

Please also take a look at the examples to help you: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md

Closing for now. But feel free to post more information in this issue.
