### ISSUE TITLE
Support for gitea pull request ?

### ISSUE THREAD

**Issue by AndreasZU** [peter-evans/create-pull-request#2728]
### Subject of the issue

I am using self hosted gitea application and gitea actions (basically github actions).
Are you willing to add support for gitea rest API pull request instead of hardcoded github.com/api/v ... ?

**Comment by peter-evans** [comment]
Hi @AndreasZU 

> Are you willing to add support for gitea rest API pull request instead of hardcoded github.com/api/v ... ?

I *might* be willing to add support for it if I'm satisfied that it would be maintainable long-term and not disrupt development for Github Actions, but I very much doubt it will be as simple as not hardcoding a URL. It would also involve setting up a test suite to run on Gitea, since I would need to make sure releases run correctly on both platforms.

I will look into this, but it might not be soon. I don't have a lot of time to investigate at the moment.

**Comment by AndreasZU** [comment]
Hi @peter-evans 

thank you for your reply!
I understand your points.

I will follow this project, maybe one day 👍

**Comment by Mai0313** [comment]
You can use this version
https://github.com/Mai0313/create-pull-request

I made it for myself since my company uses Gitea as well
