### ISSUE TITLE
push only with --force-with-lease

### ISSUE THREAD

**Issue by Ana06** [peter-evans/create-pull-request#2766]
Our bot uses this action in [the `update_package` workflow](https://github.com/mandiant/VM-Packages/blob/main/.github/workflows/update_package.yml#L60) to send regular updates and it recentely used `push --force` overwriting my commits in https://github.com/mandiant/VM-Packages/pull/864. I would like the bot to always push with `--force-with-lease` instead. I am not sure if this would a new feature request or if the use of `push --force` is a bug.

![Screenshot 2024-02-19 at 14 27 07](https://github.com/peter-evans/create-pull-request/assets/16052290/8ad5cde7-7add-4919-a27f-cf513df119c3)

Please let me know if you need any more information.

**Comment by peter-evans** [comment]
Hi @Ana06 

This action already uses `--force-with-lease`.
https://github.com/peter-evans/create-pull-request/blob/e0743ed96cb63913cf4be3cd1f5492df2ae1c6a4/src/create-pull-request.ts#L195-L199

I think you are misunderstanding what `--force-with-lease` does. It doesn't stop the branch being updated, it just prevents stale pushes that would overwrite commits that have been pushed since the last fetch.

It's a conscious design decision to allow the action to force push and update branches like this. See https://github.com/peter-evans/create-pull-request/blob/main/docs/common-issues.md#disable-force-updates-to-existing-pr-branches

The only thing I can suggest is to just to not manually edit branches that the action maintains. Or if you do, make sure to merge quickly! 😄

**Comment by Ana06** [comment]
Thanks for your answer @peter-evans! You are right @peter-evans, I was thinking the bot had removed my commits, but I had only removed some of the original commits so there were no new commits. Sorry for the confusion.
