### ISSUE TITLE
Update multiple repositories

### ISSUE THREAD

**Issue by nachitox** [peter-evans/create-pull-request#2872]
I have a central multiple repositories that depend on a single "common" one.

I've being playing with the action and I made it work for a single repository. When there's a new PUSH to master, a new PR is created for the "dependent".

Is there a "simple" way of creating a PR for each "dependent" repository?

Thanks

**Comment by peter-evans** [comment]
Hi @nachitox 

I would look at using a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) for the job that creates the pull request. In your matrix properties, use something like `repo: [dependent-repo-1, dependent-repo-2, dependent-repo-3]` so that a job is created for each.

**Comment by nachitox** [comment]
It worked perfectly.
Thank you!
