### ISSUE TITLE
[FEATURE] Add ability to enable auto-merge

### ISSUE THREAD

**Issue by gustaff-weldon** [peter-evans/create-pull-request#3007]
### Subject of the issue

We have an automated workflow that periodically updates certain variables in code, we'd like to automatically merge such PRs

**Comment by peter-evans** [comment]
Hi @gustaff-weldon 

Please see [this action](https://github.com/peter-evans/enable-pull-request-automerge) to enable automerge.

**Comment by TSenter** [comment]
Can this be revisited, since [enable-pull-request-automerge](https://github.com/peter-evans/enable-pull-request-automerge) specifically states `Using this action is no longer necessary`?

**Comment by peter-evans** [comment]
> Can this be revisited, since [enable-pull-request-automerge](https://github.com/peter-evans/enable-pull-request-automerge) specifically states `Using this action is no longer necessary`?

@TSenter What that means is that using the enable-pull-request-automerge action is not necessary anymore because the same functionality exists in the GitHub CLI. I've put a code snippet in the readme for a GitHub Actions step that uses the CLI command.

So please use either the GitHub CLI command to enable automerge, or the enable-pull-request-automerge action. I won't be adding that functionality to this action.

**Comment by TSenter** [comment]
> > Can this be revisited, since [enable-pull-request-automerge](https://github.com/peter-evans/enable-pull-request-automerge) specifically states `Using this action is no longer necessary`?
> 
> @TSenter What that means is that using the enable-pull-request-automerge action is not necessary anymore because the same functionality exists in the GitHub CLI. I've put a code snippet in the readme for a GitHub Actions step that uses the CLI command.
> 
> So please use either the GitHub CLI command to enable automerge, or the enable-pull-request-automerge action. I won't be adding that functionality to this action.

Thank you for the quick reply, that's exactly what I was looking for!
