### ISSUE TITLE
pr not generated

### ISSUE THREAD

**Issue by N6REJ** [peter-evans/create-pull-request#3031]
I'm not sure this is an issue with your action but I'm having a problem where I see the .json being generated in github virtual env but the file is always empty.  No pr is generated either.
What I want to happen ideally is the file in update-combined-json branch is populated and the pr is created then auto-merged into main.  I don't see any errors and I get the green light.
https://github.com/Bearsampp/Bearsampp/actions/runs/10031943519/job/27723002915
https://github.com/Bearsampp/Bearsampp/blob/update-combined-json/core/resources/quickpick-releases.json
https://github.com/Bearsampp/Bearsampp/blob/main/core/resources/quickpick-releases.json

**Comment by peter-evans** [comment]
Hi @N6REJ 

I think the problem is that you are trying to push changes yourself in the workflow here: https://github.com/Bearsampp/Bearsampp/actions/runs/10031943519/workflow#L83-L93

Please check the examples in the documentation. You only need to make changes and then let the action handle committing to a pull request branch and raising the PR.
