### ISSUE TITLE
Commit is not recreated if author changes

### ISSUE THREAD

**Issue by thislooksfun** [peter-evans/create-pull-request#3318]
### Subject of the issue

When the commit author changes any already open PRs are not updated to reflect that because the contents are unchanged. I suspect the same issue happens when changing the committer.

### Steps to reproduce

1. Run a workflow containing the `peter-evans/create-pull-request` action
2. Keep the resulting PR open
3. Change the workflow to have a different `author` passed to `peter-evans/create-pull-request`
4. Run the workflow again
5. The PR will still list the old author

**Comment by peter-evans** [comment]
Hi @thislooksfun 

I don't think this has ever really been an issue because the `author` and `committer` inputs are unlikely to (and probably shouldn't) be dynamic. If the configuration is changed it just means the change is reflected in the next created PR, and that will most likely be good enough.

My feeling at the moment is that it's not worth handling this edge case. It can very simply be "fixed" by just deleting the branch of any open PR and the action will recreate the PR again with the new config. If there is some legitimate use case where this doesn't cut it then I might reconsider in future.

Thank you for reporting this. It's good to review these kind of cases and document them, even if the decision is to do nothing about it. 👍

**Comment by peter-evans** [comment]
Having said that, I've just realised that the default for the `author` input [is dynamic](https://github.com/peter-evans/create-pull-request/blob/f4d66f4d5a5a7e65a185463192800c32d296ac6d/action.yml#L32)! 😄 

But actually, changing this so that a different `author` forces the PR to be updated wouldn't be good. There will definitely be cases where multiple users cause a workflow to be triggered and lead to many unnecessary force-pushes of the pull request branch. This is best left as-is I think.
