### ISSUE TITLE
##[error]The process '/opt/hostedtoolcache/Python/3.8.5/x64/bin/python' failed with exit code 1.  GitHub Action Yaml pipeline in step ' Create Pull Request'

### ISSUE THREAD

**Issue by YauheniPo** [peter-evans/create-pull-request#475]
### Subject of the issue

when performing in GitHub Action Yaml pipeline in step ' Create Pull Request', the launch crashes with an error.

http.https://github.com/.extraheader AUTHORIZATION: basic ***
/usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
/opt/hostedtoolcache/Python/3.8.5/x64/bin/python /home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py
Target repository set to YauheniPo/py_telegram_popot_bot
  stderr: 'fatal: ref HEAD is not a symbolic ref'
##[error]The checked out ref is not a valid base for a pull request. Unable to continue. Exiting.
##[error]The process '/opt/hostedtoolcache/Python/3.8.5/x64/bin/python' failed with exit code 1
/usr/bin/git config --local --add http.https://github.com/.extraheader AUTHORIZATION: basic ***

### Steps to reproduce

Link to failed execution:
https://github.com/YauheniPo/py_telegram_popot_bot/runs/926420441?check_suite_focus=true

What could be the reason for this behavior and how to fix it?

**Comment by peter-evans** [comment]
Hi @YauheniPo 

The reason is the error message here:
```
stderr: 'fatal: ref HEAD is not a symbolic ref'
##[error]The checked out ref is not a valid base for a pull request. Unable to continue. Exiting.
```
The checked out ref is not a branch, it's a merge commit. See the documentation [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#pull-request-events) about running this action in `pull_request` events.

Note that what you are attempting to do is create a pull request that merges into the current PR branch. As you could have many PRs being created at once it's necessary to modify the created `branch` name so that it applies to each PR exclusively. See [this example](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#autopep8) for reference.

**Comment by YauheniPo** [comment]
Great example and information about this!
Thanks a lot!
