### ISSUE TITLE
Poor interaction with force-pushed branches

### ISSUE THREAD

**Issue by Xyene** [peter-evans/create-pull-request#50]
First off, thanks a lot for this project &mdash; it's already saving us a ton of time 😄 

We ran into an issue when using `BRANCH_SUFFIX: none` in conjunction with workflows (human, not Github's...) that involve force-pushed feature branches. The general setup for reproduction is:

* a PR (e.g., in a cron schedule) is generated from a feature branch, but not merged
* the feature branch is force-pushed to something else
* the cron runs again, and tries to update the unmerged PR branch
* `create-pull-request` fails with something resembling:
```
Traceback (most recent call last):
  File "/create-pull-request.py", line 205, in <module>
    process_event(event_name, event_data, repo, branch, base, remote_exists)
  File "/create-pull-request.py", line 122, in process_event
    push_result = push_changes(repo.git, remote_exists, branch, commit_message)
  File "/create-pull-request.py", line 79, in push_changes
    git.rebase('-Xtheirs', '-')
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git rebase -Xtheirs -
  stderr: 'Rebasing (1/1)
interactive rebase in progress; onto bda5c319
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
Last command done (1 command done):
   pick 875113bb i18n: update translations from Crowdin

No commands remaining.
You are currently rebasing branch 'update-i18n' on 'bda5c319'.

no changes added to commit
Could not apply 875113bb... i18n: update translations from Crowdin'
```

(This is a real example, taken from [here](https://github.com/DMOJ/site/commit/72a79116e291dc7737af250ea9da20ce93585f3b/checks?check_suite_id=247338311).)

The produced error message is not entirely helpful in deducing the underlying issue. While I'm unsure of what better behaviour would be, I figured I would file this in case someone else runs into it 😉

**Comment by peter-evans** [comment]
Glad you find this action useful. Thank you for raising this issue.

When using the fixed-name branch strategy (`BRANCH_SUFFIX: none`) the action needs to check out the remote branch to update it. I couldn't check out the branch without committing local changes first so it does a `git rebase` afterwards. What I imagine is happening is that during the rebase (and because of force-pushed changes) cherry-picked commits resolve to an empty diff and throws the above warning. I'll try to reproduce this but still not sure exactly what "force-pushed to something else" means in practice.

One solution might be to use the `--keep-empty` rebase option to allow empty commits to be made. Another solution might be to stop rebasing and instead `git stash` the local changes, checkout the branch, and then `git stash pop` to apply the local changes on top of the branch. If that pop resolves to an empty diff then the action can just exit without doing anything.

**Comment by peter-evans** [comment]
@Xyene I've refactored the fixed-name branch strategy to not use rebase anymore. Having the branch rebased might be convenient in some cases, but I think it would be best to avoid using it by default because users of this action won't expect that.

So instead, when using fixed-name branch strategy the action does this:
1. Stash the local changes
2. Checkout the remote branch
3. Pop the stash
4. Resolve conflicts (if any) in favour of the stashed version

I think this method should prevent the kind of error you saw occur because if there are no changes to the branch after the stash is popped the action will just exit silently. If there are conflicts, they should all be resolved in favour of the stashed version, which is most likely correct.

Please test out release `peter-evans/create-pull-request@v1.4.1` and let me know if it works for you.

**Comment by Xyene** [comment]
@peter-evans thanks, that seems to have worked well!

> I'll try to reproduce this but still not sure exactly what "force-pushed to something else" means in practice.

In our case, it was a workflow that involves rebases that change history (e.g. renaming a commit to something more descriptive, or reordering commits to make more "sense" when reading the git log) on a feature branch, in order to keep the master log as clean as possible.

> Having the branch rebased might be convenient in some cases, but I think it would be best to avoid using it by default because users of this action won't expect that.

Agreed. It might be nice to expose functionality to rebase the entire PR branch after resolving conflicts on the tip of the base branch, though. We immediately ran into a small issue where another action (using the workaround from #48) wasn't being triggered on the PR, since it was added in a _later_ commit than where the branch was created. Of course, this just required a button press in Github's UI 

Unrelated, but what are your thoughts on uploading the built Docker image to Docker Hub? Currently it takes ~1 minute to build from scratch, which isn't _that_ bad, but probably won't be getting any faster. (I guess there could be a Github Action for automatically pushing updates to Docker hub... meta ;)

I'd be happy to contribute either of the above proposals if they're something you think would generally be useful, but I'll close this issue as it's now resolved 😃

**Comment by peter-evans** [comment]
Great! Glad that worked for you.

> Agreed. It might be nice to expose functionality to rebase the entire PR branch after resolving conflicts on the tip of the base branch, though.

I'll look into adding this back as an optional feature.

> Just found the -multi version that addresses this well enough for our use-case.

I'm not sure what direction GitHub are going to take yet regarding multi-platform Actions support so I'm holding off making the `-multi` version the main version of this action. There is a bit of background here: https://github.com/peter-evans/create-pull-request/issues/40#issuecomment-534377007
You are right though, the container version startup time could be improved by pushing it to DockerHub. I might do that regardless because someone could find it useful to run outside of GitHub Actions.
