### ISSUE TITLE
Opening PR in remote repo creates PR from the token owner, not the author/triggerer

### ISSUE THREAD

**Issue by mikeparker** [peter-evans/create-pull-request#593]
Using a PAT to open a PR in a remote repo opens the PR in the name of the PAT owner rather than the author.

I'm using this action in conjunction with a manual workflow trigger (using `workflow_dispatch`) but although the commits are committed by the triggerer, the PR itself is opened by the PAT account.

Am I right in thinking this is unavoidable or is there a workaround?

**Comment by peter-evans** [comment]
Hi @mikeparker 

It is unavoidable in the sense that a PR will always be created by the user account associated with the PAT because that is the auth used by the GitHub API. The author of git commits in the PR branch is unrelated to the author of the PR. They are entirely separate things. If you want the PR to be created by a specific user you need to use a PAT associated with that account.

It sounds like you are trying to create a `workflow_dispatch` workflow that creates a PR authored by whoever triggers the workflow. I don't think that is possible because, as far as I know, there is no way to assume the identity of another user account for auth purposes. My suggestion would be to create a machine user account to associate the PAT with. All PRs would then be created by that "bot" account.

**Comment by peter-evans** [comment]
Closing this for now. Feel free to continue the conversation if you need further help.
