### ISSUE TITLE
Support setting auto-merge for PRs

### ISSUE THREAD

**Issue by ademariag** [peter-evans/create-pull-request#768]
### Support setting auto-merge for PRs

Can you add support for setting the auto-merge flag on the PRs?

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request

**Comment by peter-evans** [comment]
Hi @ademariag 

I will look into this and see what is involved. It's quite a new feature so I'm not familiar with it yet.

**Comment by peter-evans** [comment]
It looks possible, but only by using the [GraphQL API](https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge). There doesn't seem to be a REST API for the feature yet.
I'll see if I can get it working.

**Comment by peter-evans** [comment]
@ademariag I decided to create a new action for this feature for a number of reasons, but mainly because it's not quite as simple as setting a flag on an existing API this action uses. Additionally, there are very specific conditions under which the GraphQL API will work that do not appear to be documented. I think GitHub have deliberately made it not particularly easy to use because they are concerned that widespread use of auto-merge by workflows could be used to quickly propagate a malicious package.

Please see this repo for details about how to enable the feature and use it in combination with this action.
https://github.com/peter-evans/enable-pull-request-automerge

**Comment by ademariag** [comment]
thank you, it looks great I will check it out soon!

**Comment by peter-evans** [comment]
Updated the readme with a link to the new action. Considering this issue done.
