### ISSUE TITLE
New Pull Request created every time on a re-created branch with unmerged closed pull request

### ISSUE THREAD

**Issue by sf-erush** [peter-evans/create-pull-request#926]
### New Pull Request created every time on a re-created branch with unmerged closed pull request

A branch gets deleted prior to PR being merged and the PR closes. The branch is then recreated by pushing back upstream to remote on same commit as previous closed PR.  The create-pull-request seems to not want to reopen the previously closed PR and opens a new PR. 

### Steps to reproduce
- Create a work branch, commit, push to remote
- Run create-pull-request
- PR 1 open 
- Delete remote branch on github
- PR 1 closes
- Push local branch back to remote to re create branch
- Run create-pull-request
- PR 2 open (same commit SHA as PR 1)
- PR 1 still closed

Is this intended behavior?  Or is there a way to reopen PR 1 using create-pull-request? 

Thanks

**Comment by peter-evans** [comment]
Hi @sf-erush 

No, the action will not attempt to reopen closed PRs. It's intentional in the sense that I didn't imagine anyone wanting to do that. 😄 
I don't know if I would want to change the current behaviour unless there is a very compelling reason.

If you really need this behaviour you might be able to do it yourself in a workflow step prior to executing this action. If you use the GitHub API with [github-script](https://github.com/actions/github-script) to find the closed PR and just open it then I think the action will find it and update it as normal.

**Comment by sf-erush** [comment]
Cool, thanks for the reply.
