### ISSUE TITLE
Deleting branches not working

### ISSUE THREAD

**Issue by cherryleafroad** [peter-evans/create-pull-request#936]
I have a config which uses both your automerge and create pull request actions, but even though I have delete branch set to true on this one, it doesn't get deleted after it automerges.

You can see my config here:
https://github.com/cherryleafroad/Android-ImageMagick7/blob/master/.github/workflows/im-updater-bot.yml

Hope I'm not doing something wrong, but as far as I could tell it should be working

**Comment by peter-evans** [comment]
Hi @cherryleafroad 

When `delete-branch` is set to `true` the action will delete the branch in two situations:
- If the action is closing the pull request itself (because there is no longer any diff)
- If the branch remains in the remote, but there are no further changes. In this case, most likely it has been left undeleted after merging.

Your expectation seems to be that the branch should be deleted immediately after merge, but that's not how it works. The action will find and delete it next time it runs.

To get the functionality that you want I recommend enabling GitHub's own feature for deleting the head branch in the repository settings:
![image](https://user-images.githubusercontent.com/18365890/132973039-0de948a5-3af2-44b3-a7b3-41ff8ab5bb79.png)
