### ISSUE TITLE
Labels are added post create

### ISSUE THREAD

**Issue by Skarlso** [peter-evans/create-pull-request#966]
### Subject of the issue

So I saw that labels are added post create if I understand the code correctly.

This poses the following problem. If there is an action which is triggered only if a certain label is present on the PR using this condition:

```
    if: contains(github.event.pull_request.labels.*.name, '<label-name>')
```

The action will not get triggered because by the time it runs the labels haven't been applied yet but the PR is already there.

Would it be possible to refactor to create INCLUDING the labels? Thanks!

Use case:

For integration tests which will only run on certain types of PRs.

**Comment by peter-evans** [comment]
Hi @Skarlso 

Have you tried this and confirmed that the example condition you gave doesn't work? Or are you just guessing that it wouldn't work based on reading the code of this action?

GitHub's REST API actually doesn't support applying labels at the same time as creating the pull request. You can see the documentation [here](https://docs.github.com/en/rest/reference/pulls#create-a-pull-request). GitHub also have a GraphQL API that might work differently. So that could be an option if this really is a problem.

**Comment by peter-evans** [comment]
I guess you are using the `pull_request` event to check the labels of the created pull request? You can also trigger on other event types like `labeled`, `unlabeled`, etc. So you should be able to get an event for the label being added to the pull request.

See the docs here for the different event `types`:
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request

**Comment by Skarlso** [comment]
Hmm... I guess I can use labeled. Technically, it also happens. Thanks, that's a good idea actually. :) Cheers mate.
