### ISSUE TITLE
Error: Argument list too long

### ISSUE THREAD

**Issue by lfgcampos** [peter-evans/create-pull-request#991]
### Subject of the issue

While creating some very big PRs, it is failing due to the mentioned error: `Error: Argument list too long`
I've investigated a bit and seems like my `body` input is too big (bigger than GitHub's limit).

Is there a way we can truncate the body in case we hit the limit?
I can do that myself, based on the input markdown I am generating but having that out of the box would be a nice addition.

### Steps to reproduce

Try to create a PR with a HUGE body :)

**Comment by peter-evans** [comment]
Hi @lfgcampos 

This error is not returned by the GitHub API, it's a limitation of environment variables on the Actions runner. See here for further details: https://github.com/peter-evans/create-or-update-comment/issues/96#issuecomment-957030339

As described in the above linked comment, if you are using self-hosted runners you can try increasing the stack size. Otherwise, there is nothing I can do in this action because the problem occurs before the action is able to handle the content that you are passing to the `body` input. You will need to truncate it yourself.

**Comment by lfgcampos** [comment]
Thank you for the explanation @peter-evans.

I am using it together with the compress-image action and I've filled a feature request to them to provide a `minimal` output other than the whole change list.
To not bump into the issue for now, I am going to just not provide a `body` to the PR.

I am closing this issue, thank you again.
